app = "epyhia"
primary_region = "iad"

[build]
  [build.args]
    VITE_AUTH0_DOMAIN = "dev-rxbgif7bces27stj.us.auth0.com"
    VITE_AUTH0_CLIENT_ID = "JuMeYczY79wkhbvDEjUPHkuLzppxgYhW"
    VITE_AUTH0_AUDIENCE = "https://epyhia.fly.dev/api"

[env]
  PORT = "8000"

[processes]
  web = "uvicorn epyhia.api.app:app --host 0.0.0.0 --port 8000"
  worker = "python -m epyhia.queue.worker"

[deploy]
  release_command = "alembic upgrade head"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[[vm]]
  processes = ["web"]
  memory = "1gb"

[[vm]]
  processes = ["worker"]
  cpus = 2
  memory = "4gb"
