import hashlib


def _digest(*parts: object) -> str:
    joined = "|".join(str(part) for part in parts)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()


def deploy_key(brief_hash: str, brand_doc_version: int, prompt_version: str) -> str:
    """Excludes the site artifact hash: LLM generation isn't deterministic, so keying on
    generated bytes would deploy twice whenever the generation memo misses (FR-045).

    `prompt_version` is the **Web Builder's** active version — the instructions that built
    the page — never `runs.prompt_version`, which is the Strategist's version stamped at
    ingest. Keyed on the run's column, a Web-Builder-only prompt fix could not change the
    key, so the corrected page would short-circuit onto the old publication (T143, §7.2)."""
    return _digest("deploy", brief_hash, brand_doc_version, prompt_version)


def arm_charge_path_key(brief_hash: str, resolved_catalogue_hash: str) -> str:
    return _digest("arm_charge_path", brief_hash, resolved_catalogue_hash)


def stripe_product_key(brief_hash: str, product_name: str, price_minor: int, billing: str) -> str:
    return _digest("stripe_product", brief_hash, product_name, price_minor, billing)


def stripe_price_key(brief_hash: str, product_name: str, price_minor: int, billing: str) -> str:
    return _digest("stripe_price", brief_hash, product_name, price_minor, billing)


def checkout_session_key(brief_hash: str, product: str, buyer_session: str) -> str:
    return _digest("checkout_session", brief_hash, product, buyer_session)


def video_render_key(archetype_id: str, props: str, remotion_version: str) -> str:
    """MUST include the pinned Remotion version: a version upgrade must never serve stale
    output as a cache hit (FR-046)."""
    return _digest("video_render", archetype_id, props, remotion_version)


def send_email_key(brief_hash: str, template: str, recipient: str) -> str:
    return _digest("send_email", brief_hash, template, recipient)


def alias_for(brief_hash: str) -> str:
    """`epyhia-<brief_hash[:12]>.vercel.app` — a pure function of the brief hash, so the
    deploy adapter's `verify()` derives the URL it probes rather than being told it (R2)."""
    return f"epyhia-{brief_hash[:12]}.vercel.app"


# Every origin `alias_for` can ever produce, and nothing else. The buy button posts to the
# API from the deployed site, which is a different host by construction, so `/checkout` is
# the one cross-origin route in the system — and this is the shape it accepts, derived from
# the same rule the alias is (R2, DESIGN.md §6.2).
ALIAS_ORIGIN_PATTERN = r"https://epyhia-[0-9a-f]{12}\.vercel\.app"
