import uuid

import pytest
from sqlalchemy import delete, func, select
from sqlalchemy.ext.asyncio import AsyncSession

import epyhia.queue.handlers  # noqa: F401  — registers every task handler
from epyhia.agents import web_builder
from epyhia.config import settings
from epyhia.gate import gate
from epyhia.models.actions import Action
from epyhia.models.agent_cache import AgentCacheEntry
from epyhia.models.agent_calls import AgentCall
from epyhia.models.artifacts import Artifact
from epyhia.models.tasks import Task
from epyhia.queue.worker import run_once
from tests.integration.test_us1_brief_to_site import (
    FakeDeployAdapter,
    _drive_to_approval,
    _web_builder_model,
    load_brief,
)

pytestmark = pytest.mark.asyncio


@pytest.fixture(autouse=True)
def _vercel_configured(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(settings, "vercel_token", "test-token")


async def _outcomes(session: AsyncSession, run_id: uuid.UUID) -> list[tuple]:
    """Everything the cache is forbidden to influence: which actions exist, under which
    keys, in which state, with which stored evidence."""
    rows = (
        await session.execute(
            select(Action).where(Action.run_id == run_id).order_by(Action.created_at)
        )
    ).scalars().all()
    return [
        (row.id, row.action_type, row.idempotency_key, row.state, row.evidence)
        for row in rows
    ]


async def _spend(session: AsyncSession, run_id: uuid.UUID) -> tuple[int, int]:
    """(calls that reached a model, total input tokens) — the two things a hit changes."""
    priced = (
        await session.execute(
            select(func.count(), func.coalesce(func.sum(AgentCall.input_tokens), 0)).where(
                AgentCall.run_id == run_id, AgentCall.cache_hit.is_(False)
            )
        )
    ).one()
    return int(priced[0]), int(priced[1])


async def _rerun_site(session: AsyncSession, run_id: uuid.UUID) -> None:
    session.add(Task(id=uuid.uuid4(), run_id=run_id, kind="site", state="pending"))
    await session.commit()
    with web_builder.agent.override(model=_web_builder_model()):
        assert await run_once(session, kind="site")


async def test_dropping_the_cache_changes_cost_and_nothing_else(
    integration_session: AsyncSession,
) -> None:
    """The memo is a cache, not a ledger (FR-048, Principle V).

    It is allowed to miss, and this drops it outright. What must be identical either way is
    every idempotency key and every action outcome — which is only true because no gate key
    is derived from generated bytes (§7.2). If the deploy key included the site artifact
    hash, this cache would be load-bearing for idempotency, and a cache allowed to miss must
    never be load-bearing for a guarantee.
    """
    adapter = FakeDeployAdapter()
    run_id, action = await _drive_to_approval(
        integration_session, load_brief(), adapter
    )

    await gate.record_approval(integration_session, action.id, "auth0|operator")
    integration_session.add(
        Task(
            id=uuid.uuid4(),
            run_id=run_id,
            kind="resume",
            state="pending",
            payload={"action_id": str(action.id)},
        )
    )
    await integration_session.commit()
    assert await run_once(integration_session, kind="resume")

    baseline = await _outcomes(integration_session, run_id)
    assert [row[3] for row in baseline] == ["succeeded"]
    calls_before, tokens_before = await _spend(integration_session, run_id)

    # The generation was memoised on the way through.
    assert await integration_session.scalar(select(func.count()).select_from(AgentCacheEntry))

    # Warm: the memo serves the page. No model call, no tokens, same outcomes.
    await _rerun_site(integration_session, run_id)
    warm_calls, warm_tokens = await _spend(integration_session, run_id)
    assert (warm_calls, warm_tokens) == (calls_before, tokens_before)
    assert await _outcomes(integration_session, run_id) == baseline
    assert len(adapter.execute_calls) == 1

    # Cold: drop the cache entirely. The generation is paid for again.
    await integration_session.execute(delete(AgentCacheEntry))
    await integration_session.commit()
    await _rerun_site(integration_session, run_id)
    cold_calls, cold_tokens = await _spend(integration_session, run_id)

    assert cold_calls > warm_calls
    assert cold_tokens > warm_tokens

    # And nothing else moved: same actions, same keys, same states, same evidence, and the
    # world was still reached exactly once.
    assert await _outcomes(integration_session, run_id) == baseline
    assert len(adapter.execute_calls) == 1

    # The pages the two passes produced are the same bytes — the cache changed what was
    # paid, not what was built.
    site_hashes = (
        await integration_session.execute(
            select(Artifact.sha256).where(
                Artifact.run_id == run_id, Artifact.kind == "site"
            )
        )
    ).scalars().all()
    assert len(site_hashes) == 3
    assert len(set(site_hashes)) == 1
