import uuid

import httpx
import pytest
from pydantic_ai.models.test import TestModel
from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

import epyhia.queue.handlers  # noqa: F401  — registers every task handler
from epyhia.agents import web_builder
from epyhia.api.app import create_app
from epyhia.api.auth import require_operator
from epyhia.api.db import get_session
from epyhia.config import settings
from epyhia.gate import gate
from epyhia.ingest import guardrail
from epyhia.models.actions import Action
from epyhia.models.agent_cache import AgentCacheEntry
from epyhia.models.artifacts import Artifact
from epyhia.models.briefs import Brief
from epyhia.models.runs import Run
from epyhia.models.tasks import Task
from epyhia.queue.worker import run_once
from tests.integration.test_us1_brief_to_site import (
    FakeDeployAdapter,
    _drive_to_approval,
    _web_builder_model,
    load_brief,
)

pytestmark = pytest.mark.asyncio


@pytest.fixture(autouse=True)
def _vercel_configured(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(settings, "vercel_token", "test-token")


def client_for(session: AsyncSession) -> httpx.AsyncClient:
    app = create_app()
    app.dependency_overrides[get_session] = lambda: session
    app.dependency_overrides[require_operator] = lambda: {"sub": "auth0|operator"}
    return httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app), base_url="http://api.test/api"
    )


async def _approve_and_resume(session: AsyncSession, run_id: uuid.UUID, action: Action) -> None:
    await gate.record_approval(session, action.id, "auth0|operator")
    session.add(
        Task(
            id=uuid.uuid4(),
            run_id=run_id,
            kind="resume",
            state="pending",
            payload={"action_id": str(action.id)},
        )
    )
    await session.commit()
    assert await run_once(session, kind="resume")
    await session.refresh(action)


async def test_an_identical_resubmission_opens_no_second_run(
    integration_session: AsyncSession,
) -> None:
    """"Same run" means same brief hash and nothing else (FR-002). The second submission
    resolves to the first — it does not insert and it does not open a run whose effects
    would then have to be deduplicated one action at a time."""
    payload = load_brief()

    with guardrail._agent.override(model=TestModel()):
        async with client_for(integration_session) as client:
            first = await client.post("/briefs", json=payload)
            second = await client.post("/briefs", json=payload)

    assert first.status_code == 201
    assert second.status_code == 200
    body = second.json()
    assert body["deduplicated"] is True
    assert body["run_id"] == first.json()["run_id"]
    assert body["content_sha256"] == first.json()["content_sha256"]
    assert body["alias"] == first.json()["alias"]

    assert len((await integration_session.execute(select(Brief))).scalars().all()) == 1
    assert len((await integration_session.execute(select(Run))).scalars().all()) == 1
    plan_tasks = (
        await integration_session.execute(select(Task).where(Task.kind == "plan"))
    ).scalars().all()
    assert len(plan_tasks) == 1


async def test_a_rerun_whose_generated_bytes_differ_still_produces_one_deploy(
    integration_session: AsyncSession,
) -> None:
    """The deploy key is `brief + brand doc version + prompt version` and deliberately
    excludes the site artifact hash (FR-045). Generation is not deterministic, so a key over
    generated bytes would deploy a second time every time the memo missed — which is what is
    reproduced here by dropping the cache before the second pass.
    """
    payload = load_brief()
    adapter = FakeDeployAdapter()
    run_id, action = await _drive_to_approval(integration_session, payload, adapter)
    await _approve_and_resume(integration_session, run_id, action)

    assert action.state == "succeeded"
    first_key = action.idempotency_key
    assert len(adapter.execute_calls) == 1

    # The memo is allowed to miss, and this is the miss: a dropped cache, a redeploy, a new
    # process. What must not change is the number of deploys.
    await integration_session.execute(delete(AgentCacheEntry))
    integration_session.add(
        Task(id=uuid.uuid4(), run_id=run_id, kind="site", state="pending")
    )
    await integration_session.commit()

    with web_builder.agent.override(model=_web_builder_model(marker="regenerated")):
        assert await run_once(integration_session, kind="site")

    # The bytes genuinely differ — otherwise this test would pass for the wrong reason.
    site_artifacts = (
        await integration_session.execute(
            select(Artifact).where(Artifact.run_id == run_id, Artifact.kind == "site")
        )
    ).scalars().all()
    assert len(site_artifacts) == 2
    assert len({artifact.sha256 for artifact in site_artifacts}) == 2

    # And still exactly one deploy, on the first run's key, executed once.
    deploys = (
        await integration_session.execute(
            select(Action).where(Action.run_id == run_id, Action.action_type == "deploy")
        )
    ).scalars().all()
    assert len(deploys) == 1
    assert deploys[0].idempotency_key == first_key
    assert deploys[0].state == "succeeded"
    assert len(adapter.execute_calls) == 1

    # The second pass short-circuited rather than parking a second approval in front of an
    # operator who already approved this deploy.
    resumed_site = (
        await integration_session.execute(
            select(Task).where(Task.run_id == run_id, Task.kind == "site").order_by(Task.created_at)
        )
    ).scalars().all()
    assert resumed_site[-1].state == "done"
