from epyhia.gate import keys


def test_deploy_key_unchanged_when_only_generated_site_bytes_differ() -> None:
    key_a = keys.deploy_key("brief_hash_1", 1, "v1")
    key_b = keys.deploy_key("brief_hash_1", 1, "v1")
    assert key_a == key_b

    # The deploy key has no parameter for the generated bytes at all — nothing to vary.
    assert keys.deploy_key("brief_hash_1", 1, "v1") == keys.deploy_key("brief_hash_1", 1, "v1")


def test_deploy_key_changes_when_brand_doc_version_or_prompt_version_changes() -> None:
    base = keys.deploy_key("brief_hash_1", 1, "v1")
    assert keys.deploy_key("brief_hash_1", 2, "v1") != base
    assert keys.deploy_key("brief_hash_1", 1, "v2") != base


def test_video_render_key_changes_when_pinned_remotion_version_is_bumped() -> None:
    key_before = keys.video_render_key("archetype_1", "props_json", "4.0.503")
    key_after = keys.video_render_key("archetype_1", "props_json", "4.0.504")

    assert key_before != key_after
