import hashlib
import json

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

from epyhia.models.agent_cache import AgentCacheEntry


def memo_key(
    *,
    agent: str,
    model_id: str,
    prompt_version: str,
    brand_doc_version: int | None,
    scoped_inputs: dict,
) -> str:
    """`sha256(agent + model + prompt_version + brand_doc_version + scoped inputs)` (§7.3).

    `prompt_version` and `brand_doc_version` are in the key because without them, editing the
    brand doc and re-running would serve a stale hit — and the whole point of that edit is to
    regenerate (FR-012, §5.3).
    """
    payload = json.dumps(
        {
            "agent": agent,
            "model_id": model_id,
            "prompt_version": prompt_version,
            "brand_doc_version": brand_doc_version,
            "scoped_inputs": scoped_inputs,
        },
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


async def read(session: AsyncSession, key: str) -> dict | None:
    """Replay a stored structured result, or `None`.

    A `None` here is never an error and never a decision: idempotency lives in the `actions`
    table, and no gate key is derived from generated bytes (§7.2), so a miss costs a model
    call and nothing else. A cache allowed to miss must never be load-bearing for a guarantee
    (FR-048, Principle V).
    """
    return await session.scalar(
        select(AgentCacheEntry.result).where(AgentCacheEntry.key == key)
    )


async def write(session: AsyncSession, key: str, result: dict) -> None:
    """Store a result under its key. A racer that got there first keeps its row — the two
    results are memos of the same inputs, so there is nothing to reconcile."""
    await session.execute(
        pg_insert(AgentCacheEntry)
        .values(key=key, result=result)
        .on_conflict_do_nothing(index_elements=["key"])
    )
