import json
import re
import time
import uuid

from pydantic_ai import Agent
from pydantic_ai.settings import ModelSettings
from pydantic_ai.usage import RunUsage
from sqlalchemy.ext.asyncio import AsyncSession

from epyhia.agents.memo import memo_key
from epyhia.agents.memo import read as memo_read
from epyhia.agents.memo import write as memo_write
from epyhia.agents.retry import call_with_retry
from epyhia.cost.ledger import record_call
from epyhia.cost.limits import limits_for_run
from epyhia.design.fonts import ResolvedPairing
from epyhia.prompts_service import prompt_service

AGENT = "web_builder"
MODEL_ID = "claude-sonnet-5"
PROMPT_VERSION = prompt_service.active_version(AGENT)

# The revision pass is the same model doing the same work against a punch list, but it is a
# separate prompt tree — so `active_version()` and the CI genericity globs treat it as any
# other agent's — and a separate ledger name, so a cost view can say honestly what building
# a page cost and what looking at it again cost (research R10).
REVISE_AGENT = "web_builder_revise"
REVISE_PROMPT_VERSION = prompt_service.active_version(REVISE_AGENT)

# A full page exceeds the non-streaming ceiling, and the failure mode is the dangerous one:
# an SDK timeout leaves truncated HTML that is still syntactically plausible and would then
# be deployed (§8.1, FR-014). Streaming is what makes the whole document arrive.
MAX_TOKENS = 64_000

# The wall-clock ceiling on one page generation, either pass. Healthy builds land in three to
# five minutes, and the site lease is 15 — shared with two screenshots, the critic and the
# other pass — so a call still running at six minutes is not slow, it is the stalled stream
# that parked a worker for half an hour on 2026-08-13. Constant here rather than a setting:
# it is a property of what this call does, and nothing asked for it to be tunable.
CALL_BUDGET_SECONDS = 360.0

_FENCE = re.compile(r"^\s*```(?:html)?\n(?P<body>.*?)\n```\s*$", re.DOTALL | re.IGNORECASE)

agent = Agent(
    f"anthropic:{MODEL_ID}",
    instructions=prompt_service.render(AGENT, PROMPT_VERSION),
    model_settings=ModelSettings(max_tokens=MAX_TOKENS),
    # Constructing the agent must not require ANTHROPIC_API_KEY — only calling it does.
    defer_model_check=True,
)
revise_agent = Agent(
    f"anthropic:{MODEL_ID}",
    instructions=prompt_service.render(REVISE_AGENT, REVISE_PROMPT_VERSION),
    model_settings=ModelSettings(max_tokens=MAX_TOKENS),
    defer_model_check=True,
)
# No toolset at all, on either instance. The Web Builder writes markup and nothing else: the
# deploy is requested by the site handler once the artifact is stored and its grounding check
# has run, so there is no ordering in which a page reaches the world before it has been
# checked (contracts/action-gate.md §5, FR-016).
# Never set temperature/top_p/top_k — removed on Sonnet 5, and a non-default value 400s.


def _strip_fence(text: str) -> str:
    match = _FENCE.match(text)
    return match.group("body") if match else text.strip()


def scoped_inputs(
    *, brand_doc: dict, copy: dict, checkout: dict, pairing: ResolvedPairing
) -> dict:
    """Everything the builder is allowed to know, in both passes.

    `pairing` reaches the model as family names and nothing else: it writes `font-family`
    against them, and the faces themselves are injected into the finished page afterwards
    (FR-003). Font bytes are never in this prompt.
    """
    return {
        "brand_doc": brand_doc,
        "copy": copy,
        "checkout": checkout,
        "fonts": {
            slot: {"family": face.family, "stack": face.stack}
            for slot, face in (("display", pairing.display), ("body", pairing.body))
        },
    }


async def _write_page(
    session: AsyncSession,
    *,
    run_id: uuid.UUID,
    task_id: uuid.UUID | None,
    writer: Agent,
    agent_name: str,
    prompt_version: str,
    prompt: str,
    key: str,
) -> str:
    """One streamed page generation, memoised and metered. Both passes run through here so
    that the revision is the same call under a different name, never a second mechanism."""
    # Idempotency at the gate protects the world; it does not protect the bill. A resumed
    # task re-runs this generation, whose output was probably fine, and the customer pays
    # twice for it (§7.3). Nothing downstream reads this cache: the artifact is stored and
    # grounding-checked exactly as before, and the deploy key excludes the generated bytes,
    # so a hit and a miss differ in cost and in nothing else (FR-048).
    memoised = await memo_read(session, key)
    if memoised is not None:
        await record_call(
            session,
            run_id=run_id,
            task_id=task_id,
            agent=agent_name,
            model_id=MODEL_ID,
            prompt_version=prompt_version,
            input_tokens=0,
            output_tokens=0,
            cache_write_tokens=0,
            cache_read_tokens=0,
            latency_ms=0,
            cache_hit=True,
        )
        return memoised["html"]

    started = time.perf_counter()
    limits = await limits_for_run(session, run_id)

    async def generate() -> tuple[str, RunUsage]:
        # Opened *and drained* inside the retried operation. The overload that motivated this
        # arrives on the stream's first chunk, inside a response the transport already
        # returned as 200 — so a closure that handed the context manager back and let the
        # caller read it would put the failure outside the retry, which is where it was.
        async with writer.run_stream(prompt, usage_limits=limits) as result:
            return await result.get_output(), result.usage

    html, usage = await call_with_retry(
        generate, agent=agent_name, budget_seconds=CALL_BUDGET_SECONDS
    )
    latency_ms = int((time.perf_counter() - started) * 1000)

    await record_call(
        session,
        run_id=run_id,
        task_id=task_id,
        agent=agent_name,
        model_id=MODEL_ID,
        prompt_version=prompt_version,
        input_tokens=usage.input_tokens,
        output_tokens=usage.output_tokens,
        cache_write_tokens=usage.cache_write_tokens,
        cache_read_tokens=usage.cache_read_tokens,
        latency_ms=latency_ms,
        cache_hit=usage.cache_read_tokens > 0,
    )

    markup = _strip_fence(html)
    await memo_write(session, key, {"html": markup})
    return markup


async def build_site(
    session: AsyncSession,
    *,
    run_id: uuid.UUID,
    brand_doc: dict,
    brand_doc_version: int,
    copy: dict,
    checkout: dict,
    pairing: ResolvedPairing,
    task_id: uuid.UUID | None = None,
) -> str:
    """Compose one self-contained HTML document from the brand doc and the reviewed copy.

    Returns the markup. Storing it, checking it and deploying it are the handler's, so this
    function has no way to put anything into the world.

    `checkout` carries the run id, the endpoint and one slug per offering — and no price id,
    no key and nothing else from the payment processor. That is the whole reason the site and
    money stages can run in parallel, and the reason the deployed bytes stay credential-free
    by construction (FR-030, DESIGN.md §6.2).
    """
    inputs = scoped_inputs(
        brand_doc=brand_doc, copy=copy, checkout=checkout, pairing=pairing
    )
    return await _write_page(
        session,
        run_id=run_id,
        task_id=task_id,
        writer=agent,
        agent_name=AGENT,
        prompt_version=PROMPT_VERSION,
        prompt=json.dumps(inputs, ensure_ascii=False, sort_keys=True),
        key=memo_key(
            agent=AGENT,
            model_id=MODEL_ID,
            prompt_version=PROMPT_VERSION,
            brand_doc_version=brand_doc_version,
            scoped_inputs=inputs,
        ),
    )


async def revise_site(
    session: AsyncSession,
    *,
    run_id: uuid.UUID,
    brand_doc: dict,
    brand_doc_version: int,
    copy: dict,
    checkout: dict,
    pairing: ResolvedPairing,
    page: str,
    findings: list[dict],
    task_id: uuid.UUID | None = None,
) -> str:
    """One pass over a page that has been rendered and looked at, against its punch list.

    The same model on the same inputs, plus the page and the findings — so the revision is
    bound by every rule the build was, and is re-embedded, re-sized, re-grounded and re-linted
    by the handler before it is allowed to replace anything (FR-014).

    `page` is markup as the builder wrote it, never the stored page: the faces are injected
    after generation on both passes, so no font byte is in either prompt (FR-003).

    Its memo key carries the page and the findings as well as the inputs, so the revision of a
    different page is a different call. Like the build's, it is a cache and not a ledger: a
    miss costs a model call and nothing else, because no gate key derives from these bytes.
    """
    inputs = scoped_inputs(
        brand_doc=brand_doc, copy=copy, checkout=checkout, pairing=pairing
    )
    request = {**inputs, "page": page, "findings": findings}
    return await _write_page(
        session,
        run_id=run_id,
        task_id=task_id,
        writer=revise_agent,
        agent_name=REVISE_AGENT,
        prompt_version=REVISE_PROMPT_VERSION,
        prompt=json.dumps(request, ensure_ascii=False, sort_keys=True),
        key=memo_key(
            agent=REVISE_AGENT,
            model_id=MODEL_ID,
            prompt_version=REVISE_PROMPT_VERSION,
            brand_doc_version=brand_doc_version,
            scoped_inputs=request,
        ),
    )
